env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-1
      image_family: freebsd-12-0
      image: freebsd-11-3-stable-amd64-v20190801
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y evdev-proto meson ninja pkgconf
  script: 
    - meson _build
    - ninja -C _build
