env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image-family: freebsd-13-0-snap
      image-family: freebsd-12-0
      image: freebsd-11-3-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y evdev-proto autoconf automake libtool gmake pkgconf

  script: |
    ./autogen.sh
    ./configure --disable-silent-rules
    MOREFLAGS="-Werror" gmake -j all
